Robot Arm VR: HandManager Class Reference
HandManager Class Reference
Public Types
enum HandPose { IDLE , JOYSTICK_GRAB , GRAB , POINT }
The current hand animation pose.
enum HandType { LEFT , RIGHT }
Left or right hand?
Public Member Functions
Transform GetHeldObject (HandType leftRight)
Get the currently held object from the left or right hand.
void SetHeldObject (HandType leftRight, Transform heldObject)
Set the currently held object from the left or right hand.
HandPose GetCurrentPose (HandType leftRight)
Gets the current pose
void ChangePose (HandPose fromPose, HandPose toPose, HandType leftRight)
Change pose from fromPose to toPose for left/right hand.
Package Functions
void SetController (XRCustomController xrCustomController, HandType leftOrRight)
Used to fill the LeftController / RightController properties.
Properties
Animator HandAnimatorL [get, set]
Gets left hand animator
Animator HandAnimatorR [get, set]
Gets right hand animator
XRCustomController LeftController [get, private set]
Gets the Left controller.
XRCustomController RightController [get, private set]
Gets the Right controller.
static HandManager Instance [get]
Instance used for Singleton desing pattern
Private Member Functions
void Awake ()
void Start ()
void SetCurrentPose (HandType leftRight, HandPose pose)
Sets the current pose
void InitHand (HandType leftRight)
Initialize the hand
void SwitchPose (HandPose fromPose, HandPose toPose, HandType leftRight)
Switches pose from fromPose to toPose for left/right hand.
void ResetTriggers (Animator handAnimator)
Resets the animation triggers. (This ensures they don't overlap).
Private Attributes
Transform _heldObjectLeft
Holds the currently held object for left/right
Transform _heldObjectRight
HandPose _currentPoseLeft = HandPose.IDLE
HandPose _currentPoseRight = HandPose.IDLE
Static Private Attributes
static HandManager _instance
Detailed Description
Definition at line 6 of file HandManager.cs.
Member Enumeration Documentation
HandPose
enum HandManager.HandPose
The current hand animation pose.
Enumerator
IDLE
JOYSTICK_GRAB
GRAB
POINT
Definition at line 213 of file HandManager.cs.
    {
        IDLE,
        JOYSTICK_GRAB,
        GRAB,
        POINT
    }
HandType
enum HandManager.HandType
Left or right hand?
Enumerator
LEFT
RIGHT
Definition at line 224 of file HandManager.cs.
    {
        LEFT,
        RIGHT
    }
Member Function Documentation
Awake()
void HandManager.Awake () inline private
Definition at line 41 of file HandManager.cs.
    {
        _instance = this;
    }
ChangePose()
void HandManager.ChangePose (HandPose fromPose, HandPose toPose, HandType leftRight) inline
Change pose from fromPose to toPose for left/right hand.
Parameters
fromPose The pose we switch FROM.
toPose The pose we switch TO.
leftRight Left or right hand?
Definition at line 116 of file HandManager.cs.
    {
        SwitchPose(fromPose, toPose, leftRight);
    }
Referenced by CustomInteractor.OnAttachObject(), CustomInteractor.OnDetachObject(), PointAction.PointActivation(), and JoystickInteractor.SnapToJoystick().
GetCurrentPose()
HandPose HandManager.GetCurrentPose (HandType leftRight) inline
Gets the current pose
Parameters
leftRight From left or right hand?
Returns
The current pose for the left/right hand
Definition at line 82 of file HandManager.cs.
    {
        return leftRight == HandType.LEFT ? _currentPoseLeft : _currentPoseRight;
    }
Referenced by JoystickInteractor.LateUpdate(), JoystickInteractor.PressJoystick(), JoystickInteractor.RotateController(), and SwitchPose().
GetHeldObject()
Transform HandManager.GetHeldObject (HandType leftRight) inline
Get the currently held object from the left or right hand.
Parameters
leftRight Held in left or right hand?
Returns
Definition at line 56 of file HandManager.cs.
    {
        return leftRight.Equals(HandType.LEFT) ? _heldObjectLeft : _heldObjectRight;
    }
Referenced by PointAction.PointActivation(), RobotArmController.SetPressureButton(), JoystickInteractor.SnapToJoystick(), and SwitchPose().
InitHand()
void HandManager.InitHand (HandType leftRight) inline private
Initialize the hand
Parameters
leftRight Left or right hand?
Definition at line 105 of file HandManager.cs.
    {
        SwitchPose(HandPose.IDLE, HandPose.IDLE, leftRight);
    }
Referenced by Start().
ResetTriggers()
void HandManager.ResetTriggers (Animator handAnimator) inline private
Resets the animation triggers. (This ensures they don't overlap).
Parameters
handAnimator The animator in which to reset the triggers.
Definition at line 202 of file HandManager.cs.
    {
        handAnimator.ResetTrigger("Idle");
        handAnimator.ResetTrigger("Grab");
        handAnimator.ResetTrigger("JoystickGrab");
        handAnimator.ResetTrigger("Point");
    }
Referenced by SwitchPose().
SetController()
void HandManager.SetController (XRCustomController xrCustomController, HandType leftOrRight) inline package
Used to fill the LeftController / RightController properties.
Parameters
xrCustomController The controller to pass on.
leftOrRight Pass on to which hand?
Definition at line 187 of file HandManager.cs.
    {
        if (leftOrRight.Equals(HandType.LEFT))
        {
            LeftController = xrCustomController;
            return;
        }
        RightController = xrCustomController;
    }
Referenced by XRCustomController.Start().
SetCurrentPose()
void HandManager.SetCurrentPose (HandType leftRight, HandPose pose) inline private
Sets the current pose
Parameters
leftRight For left or right hand?
Definition at line 91 of file HandManager.cs.
    {
        if (leftRight.Equals(HandType.LEFT))
        {
            _currentPoseLeft = pose;
            return;
        }
        _currentPoseRight = pose;
    }
Referenced by SwitchPose().
SetHeldObject()
void HandManager.SetHeldObject (HandType leftRight, Transform heldObject) inline
Set the currently held object from the left or right hand.
Parameters
leftRight Held in left or right hand?
Returns
Definition at line 67 of file HandManager.cs.
    {
        if (leftRight.Equals(HandType.LEFT))
        {
            _heldObjectLeft = heldObject;
            return;
        }
        _heldObjectRight = heldObject;
    }
Referenced by CustomInteractor.OnAttachObject(), and CustomInteractor.OnDetachObject().
Start()
void HandManager.Start () inline private
Definition at line 46 of file HandManager.cs.
    {
        XRCustomController.OnHandAttached += InitHand;
    }
SwitchPose()
void HandManager.SwitchPose (HandPose fromPose, HandPose toPose, HandType leftRight) inline private
Switches pose from fromPose to toPose for left/right hand.
Parameters
fromPose The pose we switch FROM.
toPose The pose we switch TO.
leftRight Left or right hand?
Exceptions
ArgumentException Thrown when pose is not found
Definition at line 128 of file HandManager.cs.
    {
        Animator handAnimator = leftRight.Equals(HandType.LEFT) ? HandAnimatorL : HandAnimatorR;
        ResetTriggers(handAnimator);
        HandPose currentPose = GetCurrentPose(leftRight);
        bool canIdle = currentPose.Equals(fromPose);
        bool isIdle = currentPose.Equals(HandPose.IDLE);
        bool hasSwitched = false;
        XRCustomController currentController = leftRight.Equals(HandType.LEFT) ? LeftController : RightController;
        switch (toPose)
        {
            case HandPose.IDLE:
                if (canIdle)
                {
                    currentController.GetComponentInChildren<CapsuleCollider>().enabled = false;
                    handAnimator.SetTrigger("Idle");
                    hasSwitched = true;
                }
                break;
            case HandPose.JOYSTICK_GRAB:
                if (leftRight.Equals(HandType.RIGHT))
                {
                    handAnimator.SetTrigger("JoystickGrab");
                    hasSwitched = true;
                }
                break;
            case HandPose.GRAB:
                if (isIdle && GetHeldObject(leftRight) != null)
                {
                    handAnimator.SetTrigger("Grab");
                    hasSwitched = true;
                }
                break;
            case HandPose.POINT:
                if (isIdle)
                {
                    currentController.GetComponentInChildren<CapsuleCollider>().enabled = true;
                    handAnimator.SetTrigger("Point");
                    hasSwitched = true;
                }
                break;
            default:
                throw new ArgumentException();
        }
        if (hasSwitched)
        {
            SetCurrentPose(leftRight, toPose);
        }
    }
Referenced by ChangePose(), and InitHand().
Member Data Documentation
_currentPoseLeft
HandPose HandManager._currentPoseLeft = HandPose.IDLE private
Definition at line 39 of file HandManager.cs.
Referenced by GetCurrentPose(), and SetCurrentPose().
_currentPoseRight
HandPose HandManager._currentPoseRight = HandPose.IDLE private
Definition at line 39 of file HandManager.cs.
Referenced by GetCurrentPose(), and SetCurrentPose().
_heldObjectLeft
Transform HandManager._heldObjectLeft private
Holds the currently held object for left/right
Definition at line 20 of file HandManager.cs.
Referenced by GetHeldObject(), and SetHeldObject().
_heldObjectRight
Transform HandManager._heldObjectRight private
Definition at line 21 of file HandManager.cs.
Referenced by GetHeldObject(), and SetHeldObject().
_instance
HandManager HandManager._instance static private
Definition at line 37 of file HandManager.cs.
Referenced by Awake().
Property Documentation
HandAnimatorL
Animator HandManager.HandAnimatorL get set
Gets left hand animator
Definition at line 11 of file HandManager.cs.
{ get; set; }
Referenced by SwitchPose().
HandAnimatorR
Animator HandManager.HandAnimatorR get set
Gets right hand animator
Definition at line 15 of file HandManager.cs.
{ get; set; }
Referenced by SwitchPose().
Instance
HandManager HandManager.Instance static get
Instance used for Singleton desing pattern
Definition at line 36 of file HandManager.cs.
{ get { return _instance; } }
Referenced by PlayerController.GripPressed(), PlayerController.JoystickAxis(), JoystickInteractor.LateUpdate(), CustomInteractor.OnAttachObject(), CustomInteractor.OnDetachObject(), PointAction.PointActivation(), JoystickInteractor.PressJoystick(), JoystickInteractor.RotateController(), RobotArmController.SetPressureButton(), FlexpendantPickup.SkipTutorial(), JoystickInteractor.SnapToJoystick(), XRCustomController.Start(), PlayerController.Start(), and RobotArmController.Start().
LeftController
XRCustomController HandManager.LeftController get private set
Gets the Left controller.
Definition at line 26 of file HandManager.cs.
{ get; private set; }
Referenced by PlayerController.GripPressed(), PlayerController.JoystickAxis(), SetController(), FlexpendantPickup.SkipTutorial(), PlayerController.Start(), and SwitchPose().
RightController
XRCustomController HandManager.RightController get private set
Gets the Right controller.
Definition at line 31 of file HandManager.cs.
{ get; private set; }
Referenced by PlayerController.GripPressed(), SetController(), PlayerController.Start(), RobotArmController.Start(), and SwitchPose().
The documentation for this class was generated from the following file:
Assets/Scripts/Managers/HandManager.cs