Robot Arm VR: SuctionGripTool Class Reference
SuctionGripTool Class Reference
A toolhead for grabbing rigidbodies with the robot arm.
Public Types
enum ToolState { Release , Grab }
The states in which the suction tool head can be.
Public Member Functions
void EnableSuctionGrab (Rigidbody grabbedObject)
Causes the tool head to start attempting to grab a rigid body.
void DisableSuctionGrab ()
Releases the grabbed rigidbody and drops it.
override void SetToolState (ToolState toolState)
Public Member Functions inherited from ToolHeadBase< SuctionGripTool.ToolState >
void AttachTool (ToolHeadController toolHeadController)
Attaches the tool to a robot arm and removes it from the physics system.
void DetachTool (SelectEnterEventArgs _)
Detaches the tool from a robot arm.
void ReleaseTool (SelectExitEventArgs _)
Makes the tool usable again by the physics system.
abstract void SetToolState (int toolStateValue)
Set the current tool state using raw values.
abstract void SetToolState (TToolState toolState)
Sets the current state of the tool head.
override void SetToolState (int toolStateValue)
Set the tool's current state.
Private Member Functions
void OnTriggerStay (Collider other)
Attempts to pick up a rigidbody if no other has been picked up.
Private Attributes
Rigidbody _affectedObject
The object currently picked up.
Additional Inherited Members
Properties inherited from ToolHeadBase< SuctionGripTool.ToolState >
bool Attachable [get, set]
Determines if the tool head is attachable to an end effector.
Rigidbody Rigidbody [get, private set]
The tool head's rigidbody.
XRGrabInteractable GrabInteractable [get, private set]
The component used for handling grabbing objects.
Vector3 HeadAttachOffset [get]
The offset the toolhead should be placed at.
TToolState CurrentState [get, protected set]
Detailed Description
A toolhead for grabbing rigidbodies with the robot arm.
Definition at line 6 of file SuctionGripTool.cs.
Member Enumeration Documentation
ToolState
enum SuctionGripTool.ToolState
The states in which the suction tool head can be.
Enumerator
Release
The toolhead should not be picking up items.
Grab
The toolhead should attempt to hold onto a rigidbody.
Definition at line 73 of file SuctionGripTool.cs.
    {
        Release,
        Grab
    }
Member Function Documentation
DisableSuctionGrab()
void SuctionGripTool.DisableSuctionGrab () inline
Releases the grabbed rigidbody and drops it.
Definition at line 44 of file SuctionGripTool.cs.
    {
        if(_affectedObject != null)
        {
            _affectedObject.transform.SetParent(null, true);
            _affectedObject.useGravity = true;
            _affectedObject.isKinematic = false;
            _affectedObject = null;
        }
    }
Referenced by SetToolState().
EnableSuctionGrab()
void SuctionGripTool.EnableSuctionGrab (Rigidbody grabbedObject) inline
Causes the tool head to start attempting to grab a rigid body.
Parameters
grabbedObject
Definition at line 30 of file SuctionGripTool.cs.
    {
        if(_affectedObject == null)
        {
            _affectedObject = grabbedObject;
            grabbedObject.useGravity = false;
            grabbedObject.isKinematic = true;
            _affectedObject.transform.SetParent(this.transform, true);
        }
    }
Referenced by OnTriggerStay().
OnTriggerStay()
void SuctionGripTool.OnTriggerStay (Collider other) inline private
Attempts to pick up a rigidbody if no other has been picked up.
Parameters
other
Definition at line 17 of file SuctionGripTool.cs.
    {
        // Make sure the tool head is in the right state and the target has a rigidbody
        if (CurrentState == ToolState.Grab && _affectedObject == null && other.TryGetComponent<Rigidbody>(out var rigidbody))
        {
            EnableSuctionGrab(rigidbody);
        }
    }
SetToolState()
override void SuctionGripTool.SetToolState (ToolState toolState) inline
Definition at line 56 of file SuctionGripTool.cs.
    {
        switch (toolState)
        {
            case ToolState.Release:
                DisableSuctionGrab();
                break;
            case ToolState.Grab:
                break;
        }
        CurrentState = toolState;
    }
Referenced by ToolHeadBase< TToolState >.SetToolState().
Member Data Documentation
_affectedObject
Rigidbody SuctionGripTool._affectedObject private
The object currently picked up.
Definition at line 11 of file SuctionGripTool.cs.
Referenced by DisableSuctionGrab(), EnableSuctionGrab(), and OnTriggerStay().
The documentation for this class was generated from the following file:
Assets/Scripts/Robotics/Toolhead/SuctionGripTool.cs