Robot Arm VR: TypeWriterText Class Reference
TypeWriterText Class Reference
A mechanism to write text over a period of time in a TMP text field.
Public Member Functions
void Write (string text)
Clears the text area and writes down the text over time.
void Clear ()
Stops the active writing coroutine and clears the text area of any text.
Private Member Functions
void Awake ()
IEnumerator TextChange (string text)
Appends characters over time to the text area on a set interval.
Private Attributes
float charWaitTime
The time in seconds between each character appearing on screen.
TextMeshProUGUI textHolder
Coroutine writeCoroutine
Detailed Description
A mechanism to write text over a period of time in a TMP text field.
Definition at line 9 of file TypeWriterText.cs.
Member Function Documentation
Awake()
void TypeWriterText.Awake () inline private
Definition at line 21 of file TypeWriterText.cs.
    {
        textHolder = GetComponent<TextMeshProUGUI>();
        textHolder.text = string.Empty;
    }
Clear()
void TypeWriterText.Clear () inline
Stops the active writing coroutine and clears the text area of any text.
Definition at line 41 of file TypeWriterText.cs.
    {
        if (writeCoroutine != null)
        {
            StopCoroutine(writeCoroutine);
            writeCoroutine = null;
        }
        textHolder.text = string.Empty;
    }
Referenced by TrainingScriptManager.ChangePhase(), TrainingScriptManager.ChangeSubPhase(), TrainingScriptManager.CloseCanvas(), and Write().
TextChange()
IEnumerator TypeWriterText.TextChange (string text) inline private
Appends characters over time to the text area on a set interval.
Parameters
text The text to be written.
Definition at line 56 of file TypeWriterText.cs.
    {
        foreach (char c in text)
        {
            textHolder.text += c;
            yield return new WaitForSeconds(charWaitTime);
        }
        writeCoroutine = null;
    }
Referenced by Write().
Write()
void TypeWriterText.Write (string text) inline
Clears the text area and writes down the text over time.
Parameters
text The text to be written.
Definition at line 31 of file TypeWriterText.cs.
    {
        Clear();
        writeCoroutine = StartCoroutine(TextChange(text));
    }
Referenced by TrainingScriptManager.ChangeSubPhase().
Member Data Documentation
charWaitTime
float TypeWriterText.charWaitTime private
The time in seconds between each character appearing on screen.
Definition at line 15 of file TypeWriterText.cs.
Referenced by TextChange().
textHolder
TextMeshProUGUI TypeWriterText.textHolder private
Definition at line 17 of file TypeWriterText.cs.
Referenced by Awake().
writeCoroutine
Coroutine TypeWriterText.writeCoroutine private
Definition at line 18 of file TypeWriterText.cs.
Referenced by Clear(), TextChange(), and Write().
The documentation for this class was generated from the following file:
Assets/Scripts/Utils/TypeWriterText.cs