Robot Arm VR: RadioBroadcaster Class Reference
RadioBroadcaster Class Reference
Broadcasts to multiple radios, only plays on the closest listener.
Public Member Functions
void StartStopBroadcast ()
Starts or stops broadcast based on current broadcast state
void StopBroadcast ()
Stop broadcasting
void SwitchListener (RadioListener closest)
Switch the old closest listener for the current closest
Public Attributes
AudioClip clip
RadioListener[] listeners
Transform player
Private Member Functions
void Start ()
void StartBroadcast ()
Starts broadcasting
void Update ()
void BroadcastToClosestListener ()
Play broadcast on closest radio
RadioListener GetClosestListener ()
Gets the closest listener
Private Attributes
RadioListener oldListener
bool broadcasting
Detailed Description
Broadcasts to multiple radios, only plays on the closest listener.
Definition at line 9 of file RadioBroadcaster.cs.
Member Function Documentation
BroadcastToClosestListener()
void RadioBroadcaster.BroadcastToClosestListener () inline private
Play broadcast on closest radio
Definition at line 72 of file RadioBroadcaster.cs.
    {
        SwitchListener(GetClosestListener());
    }
Referenced by Update().
GetClosestListener()
RadioListener RadioBroadcaster.GetClosestListener () inline private
Gets the closest listener
Returns
The closest RadioListener
Definition at line 82 of file RadioBroadcaster.cs.
    {
        RadioListener closest = null;
        float shortestDist = float.MaxValue;
        foreach (RadioListener listener in listeners)
        {
            float thisDist = Vector3.Distance(player.position, listener.transform.position);
            if (thisDist < shortestDist)
            {
                shortestDist = thisDist;
                closest = listener;
            }
        }
        return closest;
    }
Referenced by BroadcastToClosestListener(), and StartBroadcast().
Start()
void RadioBroadcaster.Start () inline private
Definition at line 21 of file RadioBroadcaster.cs.
    {
        StartBroadcast();
    }
StartBroadcast()
void RadioBroadcaster.StartBroadcast () inline private
Starts broadcasting
Definition at line 42 of file RadioBroadcaster.cs.
    {
        oldListener = GetClosestListener();
        oldListener.StartPlaying(clip);
        broadcasting = true;
    }
Referenced by Start(), and StartStopBroadcast().
StartStopBroadcast()
void RadioBroadcaster.StartStopBroadcast () inline
Starts or stops broadcast based on current broadcast state
Definition at line 29 of file RadioBroadcaster.cs.
    {
        if (broadcasting)
        {
            StopBroadcast();
            return;
        }
        StartBroadcast();
    }
StopBroadcast()
void RadioBroadcaster.StopBroadcast () inline
Stop broadcasting
Definition at line 52 of file RadioBroadcaster.cs.
    {
        broadcasting = false;
        foreach (RadioListener listener in listeners)
        {
            listener.StopPlaying();
        }
    }
Referenced by StartStopBroadcast().
SwitchListener()
void RadioBroadcaster.SwitchListener (RadioListener closest) inline
Switch the old closest listener for the current closest
Parameters
closest the current closest listener
Definition at line 104 of file RadioBroadcaster.cs.
    {
        if (closest != oldListener)
        {
            oldListener.StopPlaying();
            closest.StartPlaying(clip);
            closest.SetTime(oldListener.GetTime());
            oldListener = closest;
        }
    }
Referenced by BroadcastToClosestListener().
Update()
void RadioBroadcaster.Update () inline private
Definition at line 61 of file RadioBroadcaster.cs.
    {
        if (broadcasting)
        {
            BroadcastToClosestListener();
        }
    }
Member Data Documentation
broadcasting
bool RadioBroadcaster.broadcasting private
Definition at line 19 of file RadioBroadcaster.cs.
Referenced by StartBroadcast(), StartStopBroadcast(), StopBroadcast(), and Update().
clip
AudioClip RadioBroadcaster.clip
Definition at line 12 of file RadioBroadcaster.cs.
Referenced by StartBroadcast(), and SwitchListener().
listeners
RadioListener [] RadioBroadcaster.listeners
Definition at line 14 of file RadioBroadcaster.cs.
Referenced by GetClosestListener(), and StopBroadcast().
oldListener
RadioListener RadioBroadcaster.oldListener private
Definition at line 17 of file RadioBroadcaster.cs.
Referenced by StartBroadcast(), and SwitchListener().
player
Transform RadioBroadcaster.player
Definition at line 15 of file RadioBroadcaster.cs.
Referenced by GetClosestListener().
The documentation for this class was generated from the following file:
Assets/Scripts/Sound&Music/RadioBroadcaster.cs