Robot Arm VR: PhaseChanger Class Reference
PhaseChanger Class Reference
Updates the phase changing menus in the scene
Public Member Functions
void DeactivateWarning ()
Deactivates the initial warning on the phase changing menu
void ActivatePhaseButton (int buttonNumber)
Activate a specific button on the phase changing menu
void UnlockAllButtons ()
Unlock all buttons on the phase changing menu
void LockPushingButtons ()
Disables the button after a button press
void UnlockPushingButtons ()
Enable the button after the delay is completed
Properties
static PhaseChanger Instance [get, private set]
Private Member Functions
void Awake ()
void Start ()
void Update ()
Private Attributes
GameObject[] phaseMenus
Transform[] contentHolders
float lockTimeButtons
List< GameObject > exitButtons = new List<GameObject>()
float timer
bool locked
Detailed Description
Updates the phase changing menus in the scene
Definition at line 8 of file PhaseChanger.cs.
Member Function Documentation
ActivatePhaseButton()
void PhaseChanger.ActivatePhaseButton (int buttonNumber) inline
Activate a specific button on the phase changing menu
Parameters
buttonNumber The number for the button that will be activated
Definition at line 64 of file PhaseChanger.cs.
    {
        foreach (Transform contentHolder in contentHolders)
        {
            if (!contentHolder.GetChild(buttonNumber).gameObject.activeSelf)
            {
                contentHolder.GetChild(buttonNumber).gameObject.SetActive(true);
            }
        }
    }
Referenced by TrainingScriptManager.CheckPhaseButton().
Awake()
void PhaseChanger.Awake () inline private
Definition at line 20 of file PhaseChanger.cs.
    {
        Instance = this;
    }
DeactivateWarning()
void PhaseChanger.DeactivateWarning () inline
Deactivates the initial warning on the phase changing menu
Definition at line 51 of file PhaseChanger.cs.
    {
        foreach (GameObject menu in phaseMenus)
        {
            menu.transform.GetChild(0).gameObject.SetActive(true);
            menu.transform.GetChild(1).gameObject.SetActive(false);
        }
    }
Referenced by TouchButton.OnTriggerEnter().
LockPushingButtons()
void PhaseChanger.LockPushingButtons () inline
Disables the button after a button press
Definition at line 95 of file PhaseChanger.cs.
    {
        locked = true;
        foreach (Transform content in contentHolders)
        {
            foreach (Transform child in content)
            {
                child.GetComponent<TouchButton>().locked = locked;
            }
        }
        foreach (GameObject exitButton in exitButtons)
        {
            exitButton.GetComponent<TouchButton>().locked = locked;
        }
    }
Referenced by TouchButton.OnTriggerEnter().
Start()
void PhaseChanger.Start () inline private
Definition at line 25 of file PhaseChanger.cs.
    {
        foreach (GameObject menu in phaseMenus)
        {
            exitButtons.Add(menu.transform.GetChild(0).GetChild(0).gameObject);
        }
    }
UnlockAllButtons()
void PhaseChanger.UnlockAllButtons () inline
Unlock all buttons on the phase changing menu
Definition at line 78 of file PhaseChanger.cs.
    {
        foreach (Transform content in contentHolders)
        {
            foreach (Transform child in content)
            {
                if (!child.gameObject.activeSelf)
                {
                    child.gameObject.SetActive(true);
                }
            }
        }
    }
Referenced by TouchButton.OnTriggerEnter().
UnlockPushingButtons()
void PhaseChanger.UnlockPushingButtons () inline
Enable the button after the delay is completed
Definition at line 115 of file PhaseChanger.cs.
    {
        foreach (Transform content in contentHolders)
        {
            foreach (Transform child in content)
            {
                child.GetComponent<TouchButton>().locked = locked;
            }
        }
        foreach (GameObject exitButton in exitButtons)
        {
            exitButton.GetComponent<TouchButton>().locked = locked;
        }
    }
Referenced by Update().
Update()
void PhaseChanger.Update () inline private
Definition at line 33 of file PhaseChanger.cs.
    {
        if (locked)
        {
            timer += Time.deltaTime;
        }
        if (locked && timer > lockTimeButtons)
        {
            timer = 0;
            locked = false;
            UnlockPushingButtons();
        }
    }
Member Data Documentation
contentHolders
Transform [] PhaseChanger.contentHolders private
Definition at line 11 of file PhaseChanger.cs.
Referenced by ActivatePhaseButton(), LockPushingButtons(), UnlockAllButtons(), and UnlockPushingButtons().
exitButtons
List<GameObject> PhaseChanger.exitButtons = new List<GameObject>() private
Definition at line 14 of file PhaseChanger.cs.
Referenced by LockPushingButtons(), Start(), and UnlockPushingButtons().
locked
bool PhaseChanger.locked private
Definition at line 16 of file PhaseChanger.cs.
Referenced by LockPushingButtons(), UnlockPushingButtons(), and Update().
lockTimeButtons
float PhaseChanger.lockTimeButtons private
Definition at line 12 of file PhaseChanger.cs.
Referenced by Update().
phaseMenus
GameObject [] PhaseChanger.phaseMenus private
Definition at line 10 of file PhaseChanger.cs.
Referenced by DeactivateWarning(), and Start().
timer
float PhaseChanger.timer private
Definition at line 15 of file PhaseChanger.cs.
Referenced by Update().
Property Documentation
Instance
PhaseChanger PhaseChanger.Instance static get private set
Definition at line 18 of file PhaseChanger.cs.
{ get; private set; }
Referenced by Awake(), and TouchButton.OnTriggerEnter().
The documentation for this class was generated from the following file:
Assets/Scripts/Managers/PhaseChanger.cs