Robot Arm VR: TeleportManager Class Reference
TeleportManager Class Reference
Public Member Functions
void SwitchToTeleport (float joystickY)
Switches to teleport controls if joystick Y exceeds the joystickYTreshhold.
void SwitchToTeleport ()
Switch to teleport controls
void SwitchToDirectInteraction ()
Turn off teleport controls
Public Attributes
float joystickYTreshhold
float teleportDistance
Private Member Functions
void Start ()
void RequestTeleport ()
Request a teleport
Private Attributes
Transform rayInteractor
bool teleportActivated
Detailed Description
Definition at line 7 of file TeleportManager.cs.
Member Function Documentation
RequestTeleport()
void TeleportManager.RequestTeleport () inline private
Request a teleport
Definition at line 68 of file TeleportManager.cs.
    {
        // Raycast to teleport area
        RaycastHit hit;
        LayerMask teleportLayerMask = 1<<3;
        if (Physics.Raycast(rayInteractor.transform.position, rayInteractor.transform.forward.normalized, out hit, teleportDistance,teleportLayerMask))
        {
            // If raycast hit a teleport area
            CustomTeleportArea area = hit.transform.GetComponent<CustomTeleportArea>();
            if (area != null)
            {
                // Request the teleport
                area.RequestTeleport(rayInteractor.GetComponent<XRRayInteractor>(), hit);
                TrainingScriptManager.Instance.ActivateTrigger(0);
            }
        }
    }
Referenced by SwitchToDirectInteraction().
Start()
void TeleportManager.Start () inline private
Definition at line 18 of file TeleportManager.cs.
    {
        rayInteractor = transform.Find("RayInteractor");
        rayInteractor.GetComponent<XRRayInteractor>().maxRaycastDistance = teleportDistance;
        SwitchToDirectInteraction();
    }
SwitchToDirectInteraction()
void TeleportManager.SwitchToDirectInteraction () inline
Turn off teleport controls
Definition at line 58 of file TeleportManager.cs.
    {
        RequestTeleport();
        rayInteractor.gameObject.SetActive(false);
        teleportActivated = false;
    }
Referenced by Start(), and SwitchToTeleport().
SwitchToTeleport() [1/2]
void TeleportManager.SwitchToTeleport () inline
Switch to teleport controls
Definition at line 49 of file TeleportManager.cs.
    {
        rayInteractor.gameObject.SetActive(true);
        teleportActivated = true;
    }
Referenced by SwitchToTeleport().
SwitchToTeleport() [2/2]
void TeleportManager.SwitchToTeleport (float joystickY) inline
Switches to teleport controls if joystick Y exceeds the joystickYTreshhold.
Parameters
joystickY the joystick y axis value
Definition at line 29 of file TeleportManager.cs.
    {
        if (joystickY >= joystickYTreshhold)
        {
            if (!teleportActivated)
            {
                SwitchToTeleport();
            }
            return;
        }
        if (teleportActivated)
        {
            SwitchToDirectInteraction();
        }
    }
Referenced by PlayerController.JoystickAxis().
Member Data Documentation
joystickYTreshhold
float TeleportManager.joystickYTreshhold
Definition at line 12 of file TeleportManager.cs.
Referenced by SwitchToTeleport().
rayInteractor
Transform TeleportManager.rayInteractor private
Definition at line 10 of file TeleportManager.cs.
Referenced by RequestTeleport(), Start(), SwitchToDirectInteraction(), and SwitchToTeleport().
teleportActivated
bool TeleportManager.teleportActivated private
Definition at line 16 of file TeleportManager.cs.
Referenced by SwitchToDirectInteraction(), and SwitchToTeleport().
teleportDistance
float TeleportManager.teleportDistance
Definition at line 14 of file TeleportManager.cs.
Referenced by RequestTeleport(), and Start().
The documentation for this class was generated from the following file:
Assets/Scripts/Managers/TeleportManager.cs