Robot Arm VR: RadioListener Class Reference
RadioListener Class Reference
Receives a broadcast from the radio broadcaster
Package Functions
void StopPlaying ()
void StartPlaying (AudioClip clip)
int GetTime ()
Get sample time
void SetTime (int time)
Set current sample time
Private Member Functions
void Awake ()
Private Attributes
AudioSource audioSource
Detailed Description
Receives a broadcast from the radio broadcaster
Definition at line 10 of file RadioListener.cs.
Member Function Documentation
Awake()
void RadioListener.Awake () inline private
Definition at line 15 of file RadioListener.cs.
    {
        audioSource = GetComponent<AudioSource>();
    }
GetTime()
int RadioListener.GetTime () inline package
Get sample time
Returns
The current sample time
Definition at line 35 of file RadioListener.cs.
    {
        return audioSource.timeSamples;
    }
Referenced by RadioBroadcaster.SwitchListener().
SetTime()
void RadioListener.SetTime (int time) inline package
Set current sample time
Definition at line 43 of file RadioListener.cs.
    {
        audioSource.timeSamples = time;
    }
Referenced by RadioBroadcaster.SwitchListener().
StartPlaying()
void RadioListener.StartPlaying (AudioClip clip) inline package
Definition at line 25 of file RadioListener.cs.
    {
        audioSource.clip = clip;
        audioSource.Play();
    }
Referenced by RadioBroadcaster.StartBroadcast(), and RadioBroadcaster.SwitchListener().
StopPlaying()
void RadioListener.StopPlaying () inline package
Definition at line 20 of file RadioListener.cs.
    {
        audioSource.Pause();
    }
Referenced by RadioBroadcaster.StopBroadcast(), and RadioBroadcaster.SwitchListener().
Member Data Documentation
audioSource
AudioSource RadioListener.audioSource private
Definition at line 13 of file RadioListener.cs.
Referenced by Awake(), GetTime(), StartPlaying(), and StopPlaying().
The documentation for this class was generated from the following file:
Assets/Scripts/Sound&Music/RadioListener.cs